/*
 * This file is part of Tsunami, a fork of LiquidBounce
 * (https://github.com/CCBlueX/LiquidBounce)
 *
 * Copyright (c) 2026 Tsunami contributors
 *
 * Tsunami is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Tsunami is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Tsunami. If not, see <https://www.gnu.org/licenses/>.
 */

/**
 * Writes the benchmark scene as a datapack into a world.
 *
 *   node scripts/harness/bench-scene.mjs --world Benchmark
 *   # then, in game:  /reload   and   /function bench:setup
 *
 * ## Why a datapack rather than a saved world
 *
 * The scene has to be identical on every run, on every machine, or the FPS
 * numbers are not comparable. Committing a 28MB world folder would do that but
 * is a poor thing to keep in git; a few kilobytes of commands that *rebuild*
 * the scene on demand does the same job and can be read in a diff.
 *
 * It also makes the scene re-assertable. Run `/function bench:setup` again and
 * the weather, time, entity population and camera are back exactly where they
 * started, however much you wandered around in between.
 *
 * ## What it controls, and why each one
 *
 * Every line here exists because the thing it pins down otherwise moves between
 * runs and shows up as a mod being faster or slower:
 *
 * * **Weather.** Rain cost ~140fps on the development laptop - 378 down to 235.
 *   A benchmark that rains during one run and not the other is measuring the
 *   sky. Cleared and the cycle disabled.
 * * **Time of day.** Changes lighting, and at night hostile mobs spawn. Fixed
 *   at noon with the daylight cycle off.
 * * **Mob spawning.** New entities appearing mid-run change the entity render
 *   load underneath you. Off, difficulty peaceful.
 * * **Random ticks.** Crops growing and leaves decaying rebuild chunk meshes.
 *   Set to 0.
 * * **Entity load.** Cows with `NoAI` - they render like a real mob but never
 *   move, so the count and their positions are identical every run. This is the
 *   part the entity-culling mods actually act on, so it is the part worth
 *   holding still.
 *
 * ## Placement
 *
 * The camera sits on a small stone pad above the terrain looking out over
 * forest and coastline, with the entity block filling the near-to-middle of the
 * frame and real terrain behind it. Ocean is cheap to draw, so the camera faces
 * inland deliberately.
 */

import fs from "fs";
import path from "path";
import os from "os";

const PACK_FORMAT = 107; // data_major from the 26.2 client's version.json

const args = Object.fromEntries(
  process.argv.slice(2).reduce((acc, a, i, arr) => {
    if (a.startsWith("--")) acc.push([a.slice(2), arr[i + 1]?.startsWith("--") ? true : arr[i + 1]]);
    return acc;
  }, [])
);

const world = args.world ?? "Benchmark";
const gameDir = args.gameDir ?? path.join(os.homedir(), "Documents", "Tsunami-Client", "run");
const worldDir = path.join(gameDir, "saves", world);
if (!fs.existsSync(worldDir)) {
  console.error(`world not found: ${worldDir}`);
  process.exit(1);
}

// ------------------------------------------------------------------ the scene

/** Camera. Yaw 90 faces -X; pitch 0 keeps the horizon and the entities in frame. */
const CAM = { x: 296, y: 140, z: -527, yaw: 90, pitch: 10 };

/** Entity block: 10 x 3 x 10 = 300 cows, 10-28 blocks in front of the camera. */
const HERD = {
  xs: Array.from({ length: 10 }, (_, i) => CAM.x - 10 - i * 2),
  ys: [CAM.y - 3, CAM.y, CAM.y + 3],
  zs: Array.from({ length: 10 }, (_, i) => CAM.z - 10 + i * 2),
};

const lines = [
  "# Generated by scripts/harness/bench-scene.mjs - do not edit by hand.",
  "# Rebuilds the benchmark scene exactly. Run after /reload.",
  "",
  "# --- determinism: everything below moves FPS if left alone ---",
  "# 26.2 renamed every gamerule to snake_case: doDaylightCycle is advance_time,",
  "# doWeatherCycle is advance_weather, doMobSpawning is spawn_mobs. The old",
  "# camelCase names are rejected as an incorrect argument, and a single bad name",
  "# fails the whole function to parse - which is how the first version of this",
  "# file silently did nothing at all.",
  "gamerule advance_time false",
  "gamerule advance_weather false",
  "gamerule spawn_mobs false",
  "gamerule random_tick_speed 0",
  "difficulty peaceful",
  "weather clear",
  "time set 6000",
  "",
  "# --- clear anything left from a previous run ---",
  "kill @e[type=!player]",
  "",
  "# --- camera pad ---",
  `fill ${CAM.x - 1} ${CAM.y - 1} ${CAM.z - 1} ${CAM.x + 1} ${CAM.y - 1} ${CAM.z + 1} stone`,
  "",
  `# --- entity load: ${HERD.xs.length * HERD.ys.length * HERD.zs.length} cows, NoAI so they never move ---`,
];

for (const x of HERD.xs) {
  for (const y of HERD.ys) {
    for (const z of HERD.zs) {
      lines.push(`summon cow ${x} ${y} ${z} {NoAI:1b,NoGravity:1b,Silent:1b,PersistenceRequired:1b}`);
    }
  }
}

lines.push(
  "",
  "# --- camera last, so nothing above disturbs it ---",
  `tp @s ${CAM.x} ${CAM.y} ${CAM.z} ${CAM.yaw} ${CAM.pitch}`,
  ""
);

// ------------------------------------------------------------------- writing

const packDir = path.join(worldDir, "datapacks", "tsunami-bench");
const fnDir = path.join(packDir, "data", "bench", "function");
fs.mkdirSync(fnDir, { recursive: true });

fs.writeFileSync(path.join(packDir, "pack.mcmeta"), JSON.stringify({
  pack: { pack_format: PACK_FORMAT, description: "Tsunami FPS benchmark scene" },
}, null, 2));

fs.writeFileSync(path.join(fnDir, "setup.mcfunction"), lines.join("\n"));

const entities = HERD.xs.length * HERD.ys.length * HERD.zs.length;
console.log(`wrote ${packDir}`);
console.log(`  ${lines.length} commands, ${entities} entities`);
console.log(`\nin game:  /reload    then    /function bench:setup`);
